name: Node CI

on: [push, pull_request]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [8, 10, 11, 12]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Dependences Install
      run: |
        npm install
        npm install codecov
        ./node_modules/.bin/lerna bootstrap
    - name: Run Test
      run: |
        npm run test:coverage
    - name: Codecov
      run: |
        ./node_modules/.bin/codecov -t a6e4e876-8964-4524-b1b9-87804a54f2ba

